ERROR - 2022-08-04 18:41:39 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-08-04 18:41:39 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 415.
 1 SYSTEMPATH\Database\BaseConnection.php(585): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `product_category`
WHERE `parent_pro_cat_id` = :parent_pro_cat_id:', [...], false)
 3 SYSTEMPATH\Model.php(222): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Admin\ProductCategory.php(37): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(898): App\Controllers\Admin\ProductCategory->index()
 7 SYSTEMPATH\CodeIgniter.php(468): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\ProductCategory))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(55): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-08-04 18:41:39 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\IQraw\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\IQraw\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Admin\ProductCategory), true)
#2 C:\xampp\htdocs\IQraw\system\Debug\Exceptions.php(239): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\IQraw\system\Debug\Exceptions.php(242): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\IQraw\system\Debug\Exceptions.php(126): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
in APPPATH\Views\errors\html\error_exception.php on line 96.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
